spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/final_batch
      username: root
      password: '0000'
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never