spring:
  datasource:
    hikari:
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
